Adding Documentation
MuleSoft-AI-Chain-Project/mule-ai-chain-connector pull request #50
Opened 2024-09-10 23:58 UTC by valkyrie69

2024-09-20 19:26 UTC, rstastny9 requested changes
Hi @valkyrie69, just wrapped up my initial review of the Exchange home page. Happy to review these areas of feedback together if any of my comments are unclear!

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +The MuleSoft AI Chain Connector is designed to help developers easily build and manage AI-driven agents within MuleSoft Anypoint Platform. It provides the tools and support needed to integrate Large
"help developers design, build and manage AI agents within MuleSoft Anypoint Platform."

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +The MuleSoft AI Chain Connector is designed to help developers easily build and manage AI-driven agents within MuleSoft Anypoint Platform. It provides the tools and support needed to integrate Large
Instead of "embeddings" we should probably say "vector databases" or "vector stores"

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +- Seamless Interaction with LLMs: Effortlessly integrate and utilize large language models (LLMs) for tasks such as natural language processing, text generation, and more, including advanced features
Once we write "large language models (LLMs)" once, can't we just write LLMs after that?

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +- Seamless Interaction with LLMs: Effortlessly integrate and utilize large language models (LLMs) for tasks such as natural language processing, text generation, and more, including advanced features
Seamless Interaction with LLMs: Effortlessly integrate and utilize large language models (LLMs) for tasks such as natural language processing, text generation, text classification and more complex language tasks

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +- File-Based Local Vector Stores: Create simple, file-based vector stores directly within the connector, ideal for local use or POC designs. For external vector store integration, use the dedicated V
Let's remove mention of the Vector Store connector since it will still be open source at time of launch

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +By leveraging MuleSoft’s powerful Anypoint Platform, the MAC Connector enhances AI projects with:
We've been told to avoid using the MAC acronym

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +## Integration with the MuleSoft Ecosystem
We may want to combine the last 2 sections, they are both essentially getting across the point that by offering the connector as part of Anypoint Platform customers get a ton of inherent benefits.

The first section is more technical in nature regarding how to use the connector while the second is broader marketing benefits

2024-09-20 19:26 UTC, rstastny9 commented on documentation/home.md
> +- Centralized AI Design: Design agents using Anypoint Design Center for seamless workflow integration.
Not sure if we want to explicitly call out Design Center since it's not getting a ton (or any) investment

2024-10-29 22:52 UTC, rstastny9 requested changes
Requested a few minor changes

2024-10-29 22:52 UTC, rstastny9 commented on documentation/home.md
> +The MuleSoft AI Chain Connector helps developers design, build and manage AI agents within Anypoint Platform. It provides the tools and support needed to integrate Large Language Models (LLMs), vecto
The MuleSoft AI Chain Connector enables developers to orchestrate agentic experiences from within Anypoint Platform. It provides the tools and support needed to integrate Large Language Models (LLMs), vector stores, and other advanced AI services into MuleSoft applications.

2024-10-29 22:52 UTC, rstastny9 commented on documentation/home.md
> +- Embeddings and Search: Leverage embeddings to handle tasks like text similarity, document search, and clustering, all within MuleSoft applications.
Let's remove "all within MuleSoft applications" from the end of the bullet since the lead into this section includes "into MuleSoft applications"

2024-10-29 22:52 UTC, rstastny9 commented on documentation/home.md
> +- Customizable Tooling: Use configuration files for flexible setups tailored to your needs.
"for flexible setup" instead of "for flexible setups"

2024-10-29 22:52 UTC, rstastny9 commented on documentation/home.md
> +- Comprehensive Monitoring: Track and monitor your AI agents with Anypoint Monitoring and visualization tools.
Let's move this to the last item in the list since monitoring comes after an application has been deployed and is running

2024-10-29 22:52 UTC, rstastny9 commented on documentation/home.md
> +- Add links to product doc
@valkyrie69 can you provide a link that @dipeshkumardutta-sfemu can add to link from Exchange to docs.mulesoft.com?

2024-11-08 06:52 UTC, arpitg-1 approved these changes

2024-11-11 18:23 UTC, rstastny9 requested changes
Requesting some final tweaks to the Exchange documentation

2024-11-11 18:23 UTC, rstastny9 commented on documentation/home.md
> +The MuleSoft AI Chain Connector enables developers to orchestrate agentic experiences from within Anypoint Platform. It provides the tools and support needed to integrate Large Language Models (LLMs)
Can we update the first sentence to "The MuleSoft AI Chain Connector enables developers to design, develop and manage AI agents from within Anypoint Platform"?

2024-11-11 18:23 UTC, rstastny9 commented on documentation/home.md
> +- Embeddings and Search: Leverage embeddings to handle tasks like text similarity, document search, and clustering.
Can we update the beginning of this bullet to read: "Generate and leverage embeddings"?

2024-11-11 18:23 UTC, rstastny9 commented on documentation/home.md
> +- Comprehensive AI Tools and Services: Access a wide array of AI-driven features, including Retrieval-Augmented Generation (RAG) for document retrieval, dynamic tool integration (Function Calling), a
Let's remove "for document retrieval" after introducing RAG

2024-11-11 18:23 UTC, rstastny9 commented on documentation/home.md
> +
Can we remove this space? Would like this list to be single spaced

2024-11-11 18:23 UTC, rstastny9 commented on documentation/home.md
> +- AI Lifecycle Management: Manage the entire lifecycle of AI agents, from design to deployment, using Anypoint Platform.
Let's make this the 1st bullet

2024-11-13 04:42 UTC, merged